### ISSUE TITLE
Allow user to change their own nickname, regardless of permissions

### ISSUE THREAD

**Issue by MagicTheDev** [MagicTheDev/ClashKing#21]
https://github.com/MagicTheDev/ClashKing/blob/9cae40b55ed3d978de77339726a099e5a664a006/Link%20%26%20Eval/eval.py#L53-L59

**Comment by DNAMcKnight** [comment]
this should be an easy first fix right?  just remove the permissions check alltogher?

**Comment by Westo48** [comment]
@DNAMcKnight it could be, but this may not be something that would be good from a permission perspective. If servers don't want people to change their nickname, but the bot allows people to change their nickname, then they wouldn't want that.

**Comment by DNAMcKnight** [comment]
@Westo48 yes that makes sense. Thank you.
