### ISSUE TITLE
Role & Hierarchy Permissions Check - Bot

### ISSUE THREAD

**Issue by MagicTheDev** [MagicTheDev/ClashKing#22]
https://github.com/MagicTheDev/ClashKing/blob/9cae40b55ed3d978de77339726a099e5a664a006/Link%20%26%20Eval/eval.py#L19-L26
Check that for every role that the bot may eval  - it is valid & that the bot is above it & that the bot has Manage Role perms

**Comment by DNAMcKnight** [comment]
Could you please elabortae on this one please.
